### ISSUE TITLE
Addin fails on models with unloaded links

### ISSUE THREAD

**Issue by jessiepurcey** [mattmas/AreaPlanHelper#1]
Running the addin on a file with unloaded links throws the following error:

ArgumentNullException: The input argument "document" of function 'anonymous-namespace'::FilteredElementCollector_constructor or one item in the collection is null at line 326 of file d:\r2\2017_px64\source\revit\revit...\APIFilteredElementCollectorProxy.cpp. Parameter name: document

![image001](https://user-images.githubusercontent.com/25825539/43428351-b020b03e-9412-11e8-83fe-af7f0e57c13b.jpg)

**Comment by mattmas** [comment]
Please check out the new 1.0.1 installer, which should fix this (by ignoring unloaded links).
